# Generated by Django 4.2.15 on 2024-09-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publshed_date',
            new_name='published_date',
        ),
    ]
